### ISSUE TITLE
the pytorch_model.bin file file cannot be found

### ISSUE THREAD

**Issue by Elii-hyy** [LogAIBox/BigLog#1]
hello,the pytorch_model.bin file cannot be found, the website seems to be invalid.Can you provide it again? Thanks!

**Comment by linyuan13** [comment]
> 您好，pytorch_model.bin文件无法找到，网站似乎无效。你能再提供一次吗？谢谢！

你好，请问你现在找到pytorch_model.bin文件了吗？

**Comment by momoko123412** [comment]
你好，请问你现在找到pytorch_model.bin文件了吗？

**Comment by lunyiliu** [comment]
The model link is updated: https://huggingface.co/thatbbob/BigLog/tree/main
